version: '3.8'

services:

  apache-php:
    build: ./images
    image: apache-php:latest
    container_name: d4p-apache-php
    environment:
      - VIRTUAL_HOST=php-app.local
    volumes:
      - ../php-app:/var/www/html/php-app
      - /var/www/html/php-app/vendor
      - ./etc/apache2/sites-enabled/php-app.local.conf:/etc/apache2/sites-enabled/php-app.local.conf
      - ./log/apache2/php-app.local:/var/log/apache2/php-app.local
      - ./log/php-app.local:/tmp/log
    links:
      - database

  composer:
    image: composer:latest
    container_name: d4p-composer
    volumes_from:
      - apache-php
    working_dir: /var/www/html/php-app

  database:
    image: mariadb:latest
    container_name: d4p-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/d4p:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: d4p-phpmyadmin
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - database:db

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: d4p-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"