version: '3.8'

services:

  apache-php:
    build: ./images
    image: apache-php:latest
    container_name: "${PROJECT_NAME}_apache_php"
    environment:
      - VIRTUAL_HOST=$APP_VIRTUAL_HOST
    volumes:
      - ../php-app:/var/www/html/php-app
      - /var/www/html/php-app/vendor
      - ./etc/apache2/sites-enabled/php-app.local.conf:/etc/apache2/sites-enabled/php-app.local.conf
      - ./log/apache2/php-app.local:/var/log/apache2/php-app.local
      - ./log/php-app.local:/tmp/log
    links:
      - database

  composer:
    image: composer:latest
    container_name: "${PROJECT_NAME}_composer"
    volumes_from:
      - apache-php
    working_dir: /var/www/html/php-app

  database:
    image: mariadb:latest
    container_name: "${PROJECT_NAME}_database"
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - ./data/d4p:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_phpmyadmin"
    environment:
      - VIRTUAL_HOST=$PMA_VIRTUAL_HOST
      - PMA_HOST=db
      - PMA_USER=$DB_USER
      - PMA_PASSWORD=$DB_PASSWORD
      - UPLOAD_LIMIT=1G
    links:
      - database:db

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: "${PROJECT_NAME}_nginx_proxy"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"